version: '2'

services:
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    #command: -H unix:///var/run/docker.sock --hide-label owner=portainer
    command: --hide-label owner=portainer
    restart: always
    ports:
      - 9000:9000
      - 8000:8000
    volumes:
      #- /var/run/docker.sock:/var/run/docker.sock
      - ${XDG_RUNTIME_DIR}/docker.sock:/var/run/docker.sock
      - ${DATADIR}/portainer:/data
    labels:
      #- "owner=portainer"
      - "com.centurylinklabs.watchtower.enable=true"

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: always
    volumes:
      #- /var/run/docker.sock:/var/run/docker.sock
      - ${XDG_RUNTIME_DIR}/docker.sock:/var/run/docker.sock
      - /etc/timezone:/etc/timezone:ro
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_INCLUDE_RESTARTING=true
    labels:
      #- "owner=portainer"
      - "com.centurylinklabs.watchtower.enable=true"
